### ISSUE TITLE
erro ortografico

### ISSUE THREAD

**Issue by kelsonOM** [Brunoalcau/biblioteca_system#1]
No campo "numero do periódico" no cadastro livro/período, corrigir com acento agudo a palavra número " número do periódico"

**Comment by Brunoalcau** [comment]
Kelson ja resolvi esse bug por favor verifica outros eu vou esta fazendo alteração do sistema para o documento 1.1.0 estou seguindo.

**Comment by kelsonOM** [comment]
Ok

--- Mensagem Original ---

De: "Bruno Cau" notifications@github.com
Enviado: 18 de janeiro de 2015 17:07
Para: "Brunoalcau/biblioteca_system" biblioteca_system@noreply.github.com
Cc: "kelsonOM" kelson_monteiro@hotmail.com
Assunto: Re: [biblioteca_system] erro ortografico (#1)

Kelson ja resolvi esse bug por favor verifica outros eu vou esta fazendo alteração do sistema para o documento 1.1.0 estou seguindo.

---
