### ISSUE TITLE
Cadastro de obras 

### ISSUE THREAD

**Issue by Brunoalcau** [Brunoalcau/biblioteca_system#12]
Todos os campos são obrigatórios?? @kelsonOM

**Comment by kelsonOM** [comment]
Não é uma resposta muito precisa. Alguns apenas. Vai depender muito da instituição. O q realmente é obrigatorio em toda instituição é: none do autor, nome do livro, tombo, isbn, issn

**Comment by Brunoalcau** [comment]
Cara se depende de instituição temos que rever nossa  estrategia.
@kelsonOM  @heartazazel

**Comment by kelsonOM** [comment]
Tw falei os campos obrigatórios. ..mas os outros vai depender mesmo

**Comment by heartazazel** [comment]
não tem isso de depende da instituição, tem de saber quais os que são obrigatórios indiferente de instituição, os demais são opcionais, pois a instituição vai decidir se preenche ou não.

**Comment by kelsonOM** [comment]
Ja falei os obrigatorios no comentário anterior

--- Mensagem Original ---

De: "heartazazel" notifications@github.com
Enviado: 27 de janeiro de 2015 11:10
Para: "Brunoalcau/biblioteca_system" biblioteca_system@noreply.github.com
Cc: "kelsonOM" kelson_monteiro@hotmail.com
Assunto: Re: [biblioteca_system] Cadastro de obras  (#12)

não tem isso de depende da instituição, tem de saber quais os que são obrigatórios indiferente de instituição, os demais são opcionais, pois a instituição vai decidir se preenche ou não.

---

**Comment by Brunoalcau** [comment]
Estarei fechando a issue e colocarei os campos que o @kelsonOM  comentou depois vamos amadurecer mais essa ideia
