### ISSUE TITLE
usabilidade

### ISSUE THREAD

**Issue by kelsonOM** [Brunoalcau/biblioteca_system#5]
No campo "edição" seria melhor colocar a caixa com os números ja definidos

**Comment by Brunoalcau** [comment]
não entendi por favor de exemplos sobre isso

**Comment by kelsonOM** [comment]
Como na caixa do número de tombo. Já terá o número pré definido. Nessa caixa do numero de edição também seria assim. Ao invés do usuário ter que digitar o numero da edição bastaria clicar em uma seta e escolher o número

**Comment by Brunoalcau** [comment]
tendo em vista que o usuario não sabe o numero da edição ate receber o livro. o ideal seria deixa ele digitar mesmo  @heartazazel , @kelsonOM
